apiVersion: v1
kind: Service
metadata:
  name: wave-demo
  labels:
    app.kubernetes.io/name: wave-demo
spec:
  selector:
    app.kubernetes.io/name: wave-demo
  ports:
    - name: http
      port: 9898
      targetPort: http
