apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: podinfo-prod
  name: podinfo-prod
  namespace: e2e-testcore-renderedbranchkustomize-nodes-6a65f38f
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo-prod
  template:
    metadata:
      annotations:
        prometheus.io/port: "9898"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: podinfo-prod
    spec:
      containers:
      - image: ghcr.io/stefanprodan/podinfo:6.15.0
        name: podinfo
        ports:
        - containerPort: 9898
          name: http
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
          periodSeconds: 2
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
