apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: podinfo-prod
  name: podinfo-prod
  namespace: e2e-testcore-renderedbranchkustomize-38e4df6b
spec:
  ports:
  - name: http
    port: 9898
    targetPort: http
  selector:
    app.kubernetes.io/name: podinfo-prod
