apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kardinal-test-app
    env: test
  name: kardinal-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kardinal-test-app
  template:
    metadata:
      labels:
        app: kardinal-test-app
    spec:
      containers:
      - image: ghcr.io/pnz1990/kardinal-test-app:sha-9349a3f
        name: app
        ports:
        - containerPort: 8080
