apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-testcore-reopenedprcontinues-6bcfe2ef
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.13.0
