apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-testscm-deletedsteptracksitsnewpr-25e1aae0
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.14.1
