apiVersion: v1
kind: Service
metadata:
  name: podinfo-uat
  labels:
    app.kubernetes.io/name: podinfo-uat
spec:
  selector:
    app.kubernetes.io/name: podinfo-uat
  ports:
    - name: http
      port: 9898
      targetPort: http
